# Generated by Django 5.0.6 on 2024-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uav", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uav",
            options={"verbose_name_plural": "UAVs"},
        ),
        migrations.RemoveField(
            model_name="uav",
            name="id",
        ),
        migrations.AlterField(
            model_name="uav",
            name="serial_number",
            field=models.CharField(
                help_text="Unique identifier of the UAV",
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
