# Generated by Django 5.0.6 on 2024-05-08 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uav", "0002_alter_uav_options_remove_uav_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uav",
            options={},
        ),
    ]
