# Generated by Django 5.0.6 on 2024-05-08 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uav", "0003_alter_uav_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uav",
            name="communication_system",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="durability_and_design",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="functionality",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="propulsion_system",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="security",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="sensors",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="navigation_type",
        ),
        migrations.AlterField(
            model_name="uav",
            name="availability",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="uav",
            name="brand",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="uav",
            name="category",
        ),
        migrations.AlterField(
            model_name="uav",
            name="max_flight_time",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="max_payload_capacity",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="max_range",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="max_speed",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="model",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="uav",
            name="serial_number",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Communication",
        ),
        migrations.AddField(
            model_name="uav",
            name="communication_system",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("rf", "RF (Radio Frequency Communication)"),
                    ("gsm", "GSM (Global System for Mobile Communications):"),
                    ("wifi", "WiFi (Wireless Fidelity)"),
                    ("bluetooth", "Bluetooth"),
                    ("ir", "IR (Infrared Communication)"),
                    ("satellite", "Satellite"),
                ],
                to="uav.uav",
            ),
        ),
        migrations.DeleteModel(
            name="DurabilityAndDesign",
        ),
        migrations.AddField(
            model_name="uav",
            name="durability_and_design",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("weather_resistant", "Weather Resistant"),
                    ("modular_design", "Modular Design"),
                    ("portability", "Portability"),
                ],
                to="uav.uav",
            ),
        ),
        migrations.DeleteModel(
            name="Functionality",
        ),
        migrations.AddField(
            model_name="uav",
            name="functionality",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("autonomous_flight", "Autonomous Flight"),
                    ("mapping_and_processing", "Mapping And Processing"),
                    ("package_delivery", "Package Delivery"),
                ],
                to="uav.uav",
            ),
        ),
        migrations.DeleteModel(
            name="Propulsion",
        ),
        migrations.AddField(
            model_name="uav",
            name="propulsion_system",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("propeller", "Propeller"),
                    ("jet_engine", "Jet Engine"),
                    ("turboprop_engine", "Turboprop Engine"),
                    ("internal_combustion_engine", "Internal Combustion Engine"),
                    ("electric_motor", "Electric Motor"),
                    ("rocket_engine", "Rocket Engine"),
                ],
                to="uav.uav",
            ),
        ),
        migrations.DeleteModel(
            name="Security",
        ),
        migrations.AddField(
            model_name="uav",
            name="security",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("collision_detection", "Collision Detection"),
                    ("emergency_landing", "Emergency Landing"),
                    ("restricted_flight_zones", "Restricted Flight Zones"),
                    ("data_encryption", "Data Encryption"),
                ],
                to="uav.uav",
            ),
        ),
        migrations.DeleteModel(
            name="Sensors",
        ),
        migrations.AddField(
            model_name="uav",
            name="sensors",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("thermal_camera", "Thermal Camera"),
                    ("gps", "GPS (Global Positioning System)"),
                    ("ins", "INS (Inertial Navigation System)"),
                    ("rtk", "RTK (Real-Time Kinematic)"),
                    ("lidar", "LIDAR (Light Detection and Ranging)"),
                    ("accelerometer", "Accelerometer"),
                    ("ultrasonic", "Ultrasonic"),
                    ("gyroscope", "Gyroscope"),
                    ("barometer", "Barometer"),
                    ("magnetometer", "Magnetometer"),
                    ("air_quality", "Air Quality"),
                ],
                to="uav.uav",
            ),
        ),
        migrations.AddField(
            model_name="uav",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("military", "Military Usage"),
                    ("commercial", "Commercial and Industrial Usage"),
                    ("civil", "Civil Usage"),
                    ("research", "Research and Development"),
                    ("emergency", "Emergency and Rescue"),
                    ("training", "Training and Simulation"),
                    ("transport", "Transport and Delivery"),
                ],
                to="uav.uav",
            ),
        ),
    ]
