# Generated by Django 5.0.6 on 2024-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uav", "0004_remove_uav_communication_system_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uav",
            name="category",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="communication_system",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="durability_and_design",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="functionality",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="propulsion_system",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="security",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="sensors",
        ),
        migrations.AddField(
            model_name="uav",
            name="category",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="uav",
            name="communication_system",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="uav",
            name="durability_and_design",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="uav",
            name="functionality",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="uav",
            name="propulsion_system",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="uav",
            name="security",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="uav",
            name="sensors",
            field=models.JSONField(default=list),
        ),
    ]
