# Generated by Django 5.0.6 on 2024-05-09 15:43

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branduser",
            name="address",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="branduser",
            name="company_name",
            field=models.CharField(
                max_length=100,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="branduser",
            name="password",
            field=models.CharField(
                max_length=30, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                max_length=50,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                max_length=50,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=30, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
    ]
