# Generated by Django 5.0.6 on 2024-05-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_branduser_company_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branduser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="branduser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_login",
        ),
    ]
